---
# Set update schedule for Github Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docker/cuda"
    schedule:
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "[docker] "
      # (no colon, but a trailing whitespace)
      prefix: "[docker] "

  # - package-ecosystem: "docker"
  # directory: "/docker/intel"
  # schedule:
  #   interval: "weekly"
  # commit-message:
  #   # Prefix all commit messages with "[docker] "
  #   # (no colon, but a trailing whitespace)
  #   prefix: "[docker] "
...
